repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
    -   id: yapf
        name: yapf
        description: 'Format Python code'
        entry: yapf
        language: python
        types: [python]
        args: [-i]  # -i for in-place modifications
        additional_dependencies: [toml]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types: [json]
